package tsuteto.tofufactory.core;

import cpw.mods.fml.common.ModMetadata;
import tsuteto.tofu.TofuCraftCore;

public class ModInfo
{
    public static void load(ModMetadata meta)
    {
        meta.modId = TofuCraftCore.modid;
        meta.name = "豆腐Factory Reloaded (TofuFactory Reloaded)";
        meta.description = "工業modを中心に連携要素を加える豆腐Craftのアドオンmodです。\n\n"
                + "An add-on mod for TofuCraft to collaborate mainly with industrial mods.";
        meta.version = "1.3";
        meta.credits = "Originally made by shift";
        meta.logoFile = "assets/tofufactory/logo.png";
        meta.url = "http://forum.minecraftuser.jp/viewtopic.php?f=13&t=1014";
        meta.updateUrl = "https://dl.dropboxusercontent.com/u/14577828/mcmod/update/tofufactory.json";
        meta.authorList.add("つてと (Tsuteto)");

        meta.autogenerated = false;
    }
}
